@startuml
left to right direction

actor Pegawai as emp

package Viewer as view {
	actor HRGA as hr
	actor Finance as fin
}

package SuperAdmin as SupAdm {
	actor Developer as dev
	actor AdminHR as ahr
}

usecase "Login" as login
usecase "Logout" as logout
usecase "Validasi" as validasi
usecase "Memeriksa status login" as checkuser

usecase "Pegawai Masuk" as UC1
usecase "Pegawai Pulang" as UC2
usecase "Izin" as UC3
usecase "Sakit" as UC4
usecase "Dinas" as UC5
usecase "Libur" as UC6
usecase "Pengajuan Cuti" as UC7
database "ReportAbsensi" as db1

usecase "Dashboard Pegawai" as dashEmp
usecase "Melihat Absen" as lookAb

usecase "Mengelola Lemburan" as kelLembur

validasi --> login
validasi --> logout
validasi --> checkuser
SupAdm --> db1
view --> db1
emp --> validasi
UC1 --> db1
UC2 --> db1
UC3 --> db1
UC4 --> db1
UC5 --> db1
UC6 --> db1
UC7 --> db1
UC1 <-- kelLembur
UC2 <-- kelLembur

login --> dashEmp
dashEmp --> UC1
dashEmp --> UC2
dashEmp --> UC3
dashEmp --> UC4
dashEmp --> UC5
dashEmp --> UC6
dashEmp --> UC7
dashEmp --> lookAb
dashEmp --> checkuser
db1 --> lookAb
lookAb --> db1

kelLembur --> checkuser
SupAdm --> kelLembur
hr --> kelLembur

@enduml
