"""sakits table

Revision ID: 34e7ba8a8b87
Revises: e2f2b73ce706
Create Date: 2021-07-15 02:42:51.259297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34e7ba8a8b87'
down_revision = 'e2f2b73ce706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sakit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diagnosa', sa.String(length=120), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sakit_timestamp'), 'sakit', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sakit_timestamp'), table_name='sakit')
    op.drop_table('sakit')
    # ### end Alembic commands ###
